[2024-08-29T17:06:57.423+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T17:06:57.431+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-08-29T17:06:48.624785+00:00 [queued]>
[2024-08-29T17:06:57.436+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-08-29T17:06:48.624785+00:00 [queued]>
[2024-08-29T17:06:57.436+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 3
[2024-08-29T17:06:57.454+0000] {taskinstance.py:2879} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-08-29 17:06:48.624785+00:00
[2024-08-29T17:06:57.457+0000] {standard_task_runner.py:72} INFO - Started process 30769 to run task
[2024-08-29T17:06:57.460+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-08-29T17:06:48.624785+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/zillow_analytics.py', '--cfg-path', '/tmp/tmpx5ahwznp']
[2024-08-29T17:06:57.463+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask tsk_is_file_in_s3_available
[2024-08-29T17:06:57.499+0000] {task_command.py:467} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-08-29T17:06:48.624785+00:00 [running]> on host ip-172-31-11-44.eu-west-3.compute.internal
[2024-08-29T17:06:57.572+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='says@master.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T17:06:48.624785+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-29T17:06:48.624785+00:00'
[2024-08-29T17:06:57.573+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T17:06:57.586+0000] {baseoperator.py:405} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-29T17:06:57.586+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_29082024170650.csv
[2024-08-29T17:06:57.591+0000] {base.py:84} INFO - Retrieving connection 'aws_s3_conn'
[2024-08-29T17:06:57.591+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-08-29T17:07:02.932+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_29082024170650.csv
[2024-08-29T17:07:07.941+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_29082024170650.csv
[2024-08-29T17:07:07.956+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2024-08-29T17:07:07.962+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T17:07:07.962+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-08-29T17:06:48.624785+00:00, execution_date=20240829T170648, start_date=20240829T170657, end_date=20240829T170707
[2024-08-29T17:07:07.993+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-29T17:07:08.002+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-29T17:07:08.002+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
