[2024-08-29T18:04:15.324+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T18:04:15.334+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-08-29T18:04:06.791645+00:00 [queued]>
[2024-08-29T18:04:15.340+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-08-29T18:04:06.791645+00:00 [queued]>
[2024-08-29T18:04:15.340+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 3
[2024-08-29T18:04:15.358+0000] {taskinstance.py:2879} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-08-29 18:04:06.791645+00:00
[2024-08-29T18:04:15.362+0000] {standard_task_runner.py:72} INFO - Started process 42634 to run task
[2024-08-29T18:04:15.365+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2024-08-29T18:04:06.791645+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/zillow_analytics.py', '--cfg-path', '/tmp/tmpwe7vidga']
[2024-08-29T18:04:15.367+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask tsk_is_file_in_s3_available
[2024-08-29T18:04:15.402+0000] {task_command.py:467} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2024-08-29T18:04:06.791645+00:00 [running]> on host ip-172-31-11-44.eu-west-3.compute.internal
[2024-08-29T18:04:15.471+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='says@master.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T18:04:06.791645+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-29T18:04:06.791645+00:00'
[2024-08-29T18:04:15.472+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T18:04:15.482+0000] {baseoperator.py:405} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-29T18:04:15.483+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_29082024180409.csv
[2024-08-29T18:04:15.487+0000] {base.py:84} INFO - Retrieving connection 'aws_s3_conn'
[2024-08-29T18:04:15.487+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-08-29T18:04:20.830+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_29082024180409.csv
[2024-08-29T18:04:25.843+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_29082024180409.csv
[2024-08-29T18:04:25.861+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2024-08-29T18:04:25.865+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T18:04:25.866+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=manual__2024-08-29T18:04:06.791645+00:00, execution_date=20240829T180406, start_date=20240829T180415, end_date=20240829T180425
[2024-08-29T18:04:25.905+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-29T18:04:25.920+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-29T18:04:25.929+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
