[2024-08-29T18:04:28.120+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T18:04:28.132+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-08-29T18:04:06.791645+00:00 [queued]>
[2024-08-29T18:04:28.139+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-08-29T18:04:06.791645+00:00 [queued]>
[2024-08-29T18:04:28.139+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 3
[2024-08-29T18:04:28.156+0000] {taskinstance.py:2879} INFO - Executing <Task(S3ToRedshiftOperator): tsk_transfer_s3_to_redshift> on 2024-08-29 18:04:06.791645+00:00
[2024-08-29T18:04:28.159+0000] {standard_task_runner.py:72} INFO - Started process 42764 to run task
[2024-08-29T18:04:28.162+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_transfer_s3_to_redshift', 'manual__2024-08-29T18:04:06.791645+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/zillow_analytics.py', '--cfg-path', '/tmp/tmpiau2qgxt']
[2024-08-29T18:04:28.163+0000] {standard_task_runner.py:105} INFO - Job 83: Subtask tsk_transfer_s3_to_redshift
[2024-08-29T18:04:28.196+0000] {task_command.py:467} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-08-29T18:04:06.791645+00:00 [running]> on host ip-172-31-11-44.eu-west-3.compute.internal
[2024-08-29T18:04:28.263+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='says@master.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_transfer_s3_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T18:04:06.791645+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-29T18:04:06.791645+00:00'
[2024-08-29T18:04:28.263+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T18:04:28.278+0000] {base.py:84} INFO - Retrieving connection 'aws_s3_conn'
[2024-08-29T18:04:28.280+0000] {base.py:84} INFO - Retrieving connection 'aws_s3_conn'
[2024-08-29T18:04:28.280+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-08-29T18:04:28.291+0000] {s3_to_redshift.py:194} INFO - Executing COPY command...
[2024-08-29T18:04:28.293+0000] {base.py:84} INFO - Retrieving connection 'conn_id_redshift'
[2024-08-29T18:05:49.862+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
[2024-08-29T18:05:49.867+0000] {process_utils.py:132} INFO - Sending 15 to group 42764. PIDs of all processes in the group: [42764]
[2024-08-29T18:05:49.867+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 42764
[2024-08-29T18:05:49.867+0000] {taskinstance.py:3083} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-29T18:05:49.890+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 198, in execute
    redshift_hook.run(sql, autocommit=self.autocommit)
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 452, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 574, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/redshift_sql.py", line 208, in get_conn
    return redshift_connector.connect(**conn_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/redshift_connector/__init__.py", line 394, in connect
    return Connection(
           ^^^^^^^^^^^
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/redshift_connector/core.py", line 634, in __init__
    self._usock.connect(hostport)
  File "/home/ubuntu/myenv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3085, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-08-29T18:05:49.895+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=zillow_analytics_dag, task_id=tsk_transfer_s3_to_redshift, run_id=manual__2024-08-29T18:04:06.791645+00:00, execution_date=20240829T180406, start_date=20240829T180428, end_date=20240829T180549
[2024-08-29T18:05:49.910+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T18:05:49.920+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=42764, status='terminated', exitcode=2, started='18:04:27') (42764) terminated with exit code 2
[2024-08-29T18:05:53.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T18:05:53.668+0000] {taskinstance.py:2593} INFO - Dependencies not met for <TaskInstance: zillow_analytics_dag.tsk_transfer_s3_to_redshift manual__2024-08-29T18:04:06.791645+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-08-29T18:05:53.668297+00:00 and task will be retried at 2024-08-29T18:06:04.895423+00:00.
[2024-08-29T18:05:53.676+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
