[2024-08-30T16:05:12.123+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-30T16:05:12.132+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T16:05:12.137+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available scheduled__2024-08-29T00:00:00+00:00 [queued]>
[2024-08-30T16:05:12.137+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 3
[2024-08-30T16:05:12.153+0000] {taskinstance.py:2879} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2024-08-29 00:00:00+00:00
[2024-08-30T16:05:12.156+0000] {standard_task_runner.py:72} INFO - Started process 2322 to run task
[2024-08-30T16:05:12.159+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'scheduled__2024-08-29T00:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/zillow_analytics.py', '--cfg-path', '/tmp/tmps5gx1fko']
[2024-08-30T16:05:12.160+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask tsk_is_file_in_s3_available
[2024-08-30T16:05:12.197+0000] {task_command.py:467} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available scheduled__2024-08-29T00:00:00+00:00 [running]> on host ip-172-31-11-44.eu-west-3.compute.internal
[2024-08-30T16:05:12.268+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='says@master.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-29T00:00:00+00:00'
[2024-08-30T16:05:12.268+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-30T16:05:12.279+0000] {baseoperator.py:405} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-30T16:05:12.279+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_30082024160249.csv
[2024-08-30T16:05:12.283+0000] {base.py:84} INFO - Retrieving connection 'aws_s3_conn'
[2024-08-30T16:05:12.283+0000] {connection_wrapper.py:388} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-08-30T16:05:17.635+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_30082024160249.csv
[2024-08-30T16:05:22.645+0000] {s3.py:118} INFO - Poking for key : s3://cleaned-endtoend-csv-bucket/response_data_30082024160249.csv
[2024-08-30T16:05:22.660+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2024-08-30T16:05:22.665+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-30T16:05:22.665+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, run_id=scheduled__2024-08-29T00:00:00+00:00, execution_date=20240829T000000, start_date=20240830T160512, end_date=20240830T160522
[2024-08-30T16:05:22.689+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-30T16:05:22.704+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-30T16:05:22.713+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
